name: java-build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build the package
        run: mvn -B package --file pom.xml
      - name: Publish to Github Packages
        run: mvn -B deploy -Dpackage.repository=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}